global:
  resolve_timeout: 1m

route:
  receiver: "gmail-notifications"

receivers:
  - name: "gmail-notifications"
    email_configs:
      - to: vanderleiromera@gmail.com
        from: vanderleiromera@gmail.com
        smarthost: smtp.gmail.com:587
        # não funcionou com variaveis
        #auth_username: "$ALERT_AUTH"
        #auth_identity: "$ALERT_AUTH"
        #auth_password: "$ALERT_PASS"
        send_resolved: true
        require_tls: true
