version: "3.8"

services:
  proxy:
    image: traefik:v2.6
    networks:
      shared:
      private:
      public:
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    depends_on:
      - dockersocket
    restart: unless-stopped
    privileged: true
    tty: true
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config.yml:/etc/traefik/config.yml:ro
      - ./certs:/etc/certs:rw,Z
      - acme:/etc/traefik/acme:rw,Z
    #
    # Note: when used in docker-compose.yml all dollar signs in the hash need to be doubled for escaping.
    # To create user:password pair, it's possible to use this command:
    # echo $(htpasswd -nB traefik-admin) | sed -e s/\\$/\\$\\$/g
    #
    # Also note that dollar signs should NOT be doubled when they not evaluated (e.g. Ansible docker_container module).
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.routers.proxy.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.middlewares.auth-test.basicauth.users=test:$$2a$$12$$do7J8NXD3yFluZqiyOsQgOdr/1pdkuLqEnqXHhUtjAfvREOjJiWba"
      - "traefik.http.routers.proxy.tls.certResolver=cloudflare"
      - "traefik.http.routers.proxy.tls.domains[0].main=$TRAEFIK_DOMAIN"
      - "traefik.http.routers.proxy.tls.domains[0].sans=$TRAEFIK_SUB_DOMAIN"
      - "traefik.http.routers.proxy.entrypoints=https"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.routers.proxy.middlewares=auth-test"

  dockersocket:
    image: tecnativa/docker-socket-proxy
    privileged: true
    networks:
      private:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    restart: unless-stopped

networks:
  shared:
    internal: true
    driver_opts:
      encrypted: 1

  private:
    internal: true
    driver_opts:
      encrypted: 1

  public:

volumes:
  acme:
