name: ci
on:
  push:
    branches: [main]

env:
  TEST_TAG: vanderleiromera/doodba14_odoo:test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: ./odoo
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args: ODOO_VERSION=14.0

      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}

      - name: Bump version and push tag
        id: tagging
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.DOO_GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./odoo
          file: ./odoo/Dockerfile
          platforms: linux/amd64
          tags: vanderleiromera/doodba14_odoo:${{ steps.tagging.outputs.new_version }}
          build-args: ODOO_VERSION=14.0
