name: pre-test

on:
  pull_request:
  push:
    branches:
      - ci-test
  workflow_dispatch:
    inputs:
      testci:
        description: "Test-CI"
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.DOO_GITHUB_TOKEN }}
  TEST_TAG: vanderleiromera/doodba14_odoo:test

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.1.0
        with:
          # The pylint-odoo version we use here does not support python 3.10
          # https://github.com/OCA/oca-addons-repo-template/issues/80
          # We also need to pin to an older version of python for older odoo versions
          # where we are not using black > 21. Older black versions won't work with
          # Python 3.9.8+, and we can't bump black without reformatting.
          python-version: "3.9.7"
      - uses: pre-commit/action@v2.0.3

  test-image:
    needs: pre-commit
    runs-on: ubuntu-latest
    services:
      db:
        image: ghcr.io/tecnativa/postgres-autoconf:13-alpine
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoopassword
        ports:
          - 5432:5432

        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      # Shared steps
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0Fetch all history for all tags and branches

      - name: QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Bump version and push tag
        id: tagging
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.DOO_GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: ./odoo
          load: true
          build-args: ODOO_VERSION=14.0
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run --network ${{ job.container.network }} --rm ${{ env.TEST_TAG }} odoo --stop-after-init -i base

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./odoo
          file: ./odoo/Dockerfile
          no-cache: true
          platforms: linux/amd64
          tags: vanderleiromera/doodba14_odoo:${{ steps.tagging.outputs.new_version }}
          build-args: ODOO_VERSION=14.0
